export const ITEMS = {
    GET_ITEMS_PENDING:"GET_ITEMS_PENDING",
    GET_ITEMS_SUCCESS:"GET_ITEMS_SUCCESS",
    GET_ITEMS_ERROR:"GET_ITEMS_ERROR",
    ITEM_SELECT:"ITEM_SELECT"
};


export const CART = {
    CART_ADD:"CART_ADD"
}