export const ITEMS = {
    GET_ITEMS_PENDING:"GET_ITEMS_PENDING",
    GET_ITEMS_SUCCESS:"GET_ITEMS_SUCCESS",
    GET_ITEMS_ERROR:"GET_ITEMS_ERROR",
    ITEM_SELECT:"ITEM_SELECT"
};


export const CART = {
    CART_GET:"CART_GET",
    CART_ADD:"CART_ADD",
    CART_DELETE:"CART_DELETE"
};

export const ORDER = {
    CHANGE_NAME:"ORDER_CHANGE_NAME",
    CHANGE_SURNAME:"ORDER_CHANGE_SURNAME",
    CHANGE_PHONE:"ORDER_CHANGE_PHONE",
    CHANGE_ADDRESS:"ORDER_CHANGE_ADDRESS",
};